# 与此文件相关命令带 --env-file .env.docker 参数 eg: docker compose --env-file .env.docker up -d
services:
  postgres:
    image: timescale/timescaledb:2.16.1-pg15
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:7.2-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
