"""sync corporate_actions changes

Revision ID: 401266640e95
Revises: 564e4597a896
Create Date: 2026-07-08 11:22:02.284330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401266640e95'
down_revision: Union[str, Sequence[str], None] = '564e4597a896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('cash_per_share', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stock_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rights_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rights_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'ex_date', 'action_type', name='uq_corporate_actions_symbol_ex_date_action_type')
    )
    op.execute("DROP INDEX IF EXISTS idx_klines_symbol_period")
    op.execute("DROP INDEX IF EXISTS klines_ts_idx")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('klines_ts_idx'), 'klines', [sa.literal_column('ts DESC')], unique=False)
    op.create_index(op.f('idx_klines_symbol_period'), 'klines', ['symbol', 'period', sa.literal_column('ts DESC')], unique=False)
    op.drop_table('corporate_actions')
    # ### end Alembic commands ###
