"""create market tables

Revision ID: 564e4597a896
Revises: c89a5eebe84a
Create Date: 2026-07-06 10:38:30.924502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564e4597a896'
down_revision: Union[str, Sequence[str], None] = 'c89a5eebe84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period', 'ts', name='pk_klines')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_items_watchlist_id_symbol')
    )
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    # 将普通表转换为 TimescaleDB 超表，实现按时间自动分区。
    # 如果不转换，随着 K 线数据量增长，查询性能会急剧下降。
    op.execute("SELECT create_hypertable('klines', 'ts')")
    # 创建复合索引，覆盖最常见的查询模式：查某交易对某周期的历史 K 线。
    # 虽然超表已经按 ts 分区，但分区只负责粗粒度的时间过滤，
    # 索引负责精确定位到具体的 symbol 和 period，两者互补。
    op.execute("CREATE INDEX idx_klines_symbol_period ON klines (symbol, period, ts DESC)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_table('klines')
    # ### end Alembic commands ###
